### PR TITLE
API keys should never be public

### PR DESCRIPTION
**Pull request by w3bdesign**
Please see https://create-react-app.dev/docs/adding-custom-environment-variables/

### CODE REVIEW

**Comment by Thananjaya** [comment]
@w3bdesign Thanks man, I will follow the docs and merge this pull request. And also, Can I ask questions if there are any doubts regarding this subject.

**Comment by w3bdesign** [comment]
Yes @Thananjaya,

Just tag me and ask me if you have any questions.

Can I ask what you are using for deployment? Heroku? Netlify? Or something else?

**Comment by Thananjaya** [comment]
I have opted for Heroku, what's your choice? @w3bdesign

**Comment by w3bdesign** [comment]
> 
> 
> I have opted for Heroku, what's your choice? @w3bdesign

@Thananjaya I am using Netlify for React and HTML websites and Heroku for sites that use Node.js and Express.

I am also experimenting with DigitalOcean and Vultr for Docker-based solutions.

**Pull request closed without merging**
